### ISSUE TITLE
Test the datasets DukeMTMC-reID,it takes error,do you know why?

### ISSUE THREAD

**Issue by Yx1322441675** [wangguanan/HOReID#19]
I trained the dataset DukeMTMC-reID,after that,i test the generated 'pkl' documents,but it takes error.I want to know how can i modify it. Maybe you can help me with it.  Thank you.

(horeid) goo@goo-Z390-GAMING-X:~/yx/HOReID/HOReID-master$ python main.py --mode test \--resume_test_path /home/goo/yx/HOReID/HOReID-master/result-DukeMTMC/MODELS --resume_test_epoch 119 \--duke_path /home/goo/yx/datayx/DukeMTMC-reID --output_path ./result-DukeMTMC
Traceback (most recent call last):
  File "main.py", line 162, in <module>
    main(config)
  File "main.py", line 14, in main
    loaders = Loaders(config)
  File "/home/goo/yx/HOReID/HOReID-master/core/data_loader/__init__.py", line 49, in __init__
    self._load()
  File "/home/goo/yx/HOReID/HOReID-master/core/data_loader/__init__.py", line 54, in _load
    train_samples = self._get_train_samples(self.train_dataset)
  File "/home/goo/yx/HOReID/HOReID-master/core/data_loader/__init__.py", line 64, in _get_train_samples
    samples = Samples4Duke(train_samples_path)
  File "/home/goo/yx/HOReID/HOReID-master/core/data_loader/dataset.py", line 23, in __init__
    samples = self._load_images_path(self.samples_path)
  File "/home/goo/yx/HOReID/HOReID-master/core/data_loader/dataset.py", line 52, in _load_images_path
    root_path, _, files_name = os_walk(folder_dir)
TypeError: cannot unpack non-iterable NoneType object

**Comment by wangguanan** [comment]
seem that the folder_dir is null
could you please check your given duke dataset path?

path can be set as below: 
( remember to replace path/to/occluded/duke with your path)
``` 
python main.py --mode train \
--duke_path path/to/occluded/duke \
--output_path ./results 
```

the occluded dataset can be download from the official [link](https://github.com/lightas/Occluded-DukeMTMC-Dataset)
(you need to run a script to process the original DukeMTMC-reID dataset to get an occluded version)

or try my post-processed occluded duke dataset, just unzip and get final occluded-duke dataset
[link](https://drive.google.com/file/d/1rba7DluxolBl1QD5nTF7iX3UBTGSDp06/view?usp=sharing)
