### ISSUE TITLE
你好，问您一个问题，对于个人数据集（duke格式的）该怎么准备呢？ 

### ISSUE THREAD

**Issue by tianyuluan** [wangguanan/HOReID#7]
我现在已经按照您的步骤将数据集转化成了Occluded-Duke的数据格式，下载您提供的预训练模型，但是运行的时候遇到了这样的问题：
Traceback (most recent call last):
  File "/home/lty/lty/HOReID-master/main.py", line 151, in <module>
    main(config)
  File "/home/lty/lty/HOReID-master/main.py", line 56, in main
    _, results = train_an_epoch(config, base, loaders, current_epoch)
  File "/home/lty/lty/HOReID-master/core/train.py", line 26, in train_an_epoch
    ide_loss = base.compute_ide_loss(cls_score_list, pids, keypoints_confidence)
  File "/home/lty/lty/HOReID-master/core/base.py", line 100, in compute_ide_loss
    loss_i = self.ide_creiteron(score_i, pids)
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lty/lty/HOReID-master/tools/loss.py", line 33, in forward
    targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151

**我猜测是因为，config中的pid_num的原因**
当我修改了pid_num为我们数据的pid数后，报错如下：
size mismatch for module.classifier_0.classifier.weight: copying a param with shape torch.Size([702, 2048]) from checkpoint, the shape in current model is torch.Size([750, 2048]).
......

请问我该怎么做？

**Comment by wangguanan** [comment]
应该把 id 数量设置成 702，这样还报错吗？

如果还是报错，可能是因为你自己的的数据，有些图像的 label >701 造成的，你可以去print一下你每个图像的 pid，并分析一下是什么原因造成 label > 701 的。
